apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      # Реестр слушает внутри контейнера на 5000,
      # но с TLS (см. env переменные).
      addr: :5000
      headers:
        X-Content-Type-Options: ["nosniff"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            # Включаем TLS у самого registry
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/tls.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/tls.key
            - name: REGISTRY_CONFIGURATION_PATH
              value: /etc/docker/registry/config.yml
          volumeMounts:
            - name: storage
              mountPath: /var/lib/registry
            - name: config
              mountPath: /etc/docker/registry
            - name: certs
              mountPath: /certs
              readOnly: true
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /v2/
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /v2/
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: registry-data
        - name: config
          configMap:
            name: registry-config
            items:
              - key: config.yml
                path: config.yml
        - name: certs
          secret:
            secretName: registry-tls
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: ClusterIP
  selector:
    app: registry
  ports:
    # Клиенты будут ходить на 443 без указания порта.
    - name: https
      port: 443
      targetPort: 5000
