apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  runtimeClassName: nvidia
  restartPolicy: OnFailure
  containers:
  - name: cuda-container
    image: nvidia/cuda:12.0.0-base-ubuntu22.04
    command: ["/bin/sh", "-c"]
    args: ["nvidia-smi && echo 'GPU Test Success' && sleep 3600"]
    resources:
      limits:
        nvidia.com/gpu: 1
